---
- name: Installing cQube
  hosts: localhost
  gather_facts: true
  remote_user: root
  vars_files:
    - ../config.yml
    - ../memory_config.yml
    - ../.version

  roles:
          - datasource
          - createdb
          - python_flask
          - { role: kong, tags: install }
          - keycloak
          - nifi_install
          - { role: nifi_params, tags: install }
          - { role: nifi_data_sources, tags: install }

          - angular
          - angular_admin

          - { role: nifi_scheduler, tags: install }
          - cqube_version
