---
- name: Upgrading cQube
  hosts: localhost
  gather_facts: true
  remote_user: root
  vars_files:
    - ../upgradation_config.yml  
    - ../memory_config.yml
    - ../.version
    
  roles: 
          - datasource
          - createdb
          - python_flask
          - { role: kong, tags: update }
          - keycloak
          - nifi_install
          - { role: nifi_params, tags: update }
          - { role: nifi_data_sources, tags: update } 

          - angular
          - angular_admin

          - cqube_version
