---
- name: Stoping the admin_server_side app
  become: yes
  shell: pm2 stop admin_server_side
  tags: update

- name: Delete admin_server_side directory
  file:
    path: "{{ base_dir }}/cqube/admin_dashboard/server_side"
    state: absent
  tags: update

- name: Creating the admin's server_side Directory for the installation
  file: 
    path: "{{ base_dir }}/cqube/admin_dashboard/server_side"
    owner: "{{ system_user_name }}"
    group: "{{ system_user_name }}"
    recurse: yes
    state: directory
  tags: [ install, update ]

- name: copying admin's server-side script
  shell: "cp -R ../../development/admin/server-side/* {{base_dir}}/cqube/admin_dashboard/server_side"
  tags: [ install, update ]

- name: NodeJS dependencies install
  npm:
    path: "{{base_dir}}/cqube/admin_dashboard/server_side"
  tags: [ install, update ]

- name: Creating environmental variables
  file:
    path: "{{base_dir}}/cqube/admin_dashboard/server_side/.env"
    state: touch
    mode: u+rw,g+rw,o+rw
  tags: [ install, update ]

- name: Loading required data inside .env file
  blockinfile:
    path: "{{base_dir}}/cqube/admin_dashboard/server_side/.env"
    block: |
      PORT = 3001
      BASE_DIR = "{{ base_dir }}"
      BASEURL = "http://{{ local_ipv4_address}}:5000"

      KEYCLOAK_HOST = "https://{{ api_endpoint }}"
      KEYCLOAK_REALM = "{{ realm_name }}"
      KEYCLOAK_CLIENT= "{{ admin_app_client_id }}"
      KEYCLOAK_USER= "{{ keycloak_adm_user }}"
      PASSWORD= "{{ keycloak_adm_passwd }}"
      GRANT_TYPE= "password"

      NIFI_PROCESSORS= "crc_transformer,semester_transformer,student_attendance_transformer,diksha_transformer,infra_transformer,static_data_transformer,udise_transformer,pat_transformer,composite_transformer,healthcard_transformer,teacher_attendance_transformer"
      NIFI_URL= "http://localhost:8096/nifi-api"

      NODE_ENV= "DEVELOPMENT"
      SYSTEM_USERNAME = {{ system_user_name }}
      LOG= "console"
      LOG_DIRECTORY= ""
      KONG_BASE_URL = "http://localhost:8001/consumers"
  tags: [ install, update ]


